'use strict'; /*jshint browser:true, es5:true*/
define(function(){
var E = {
    app_name: {message: 'Hola أفضل الإنترنت'},
    app_desc: {message: 'لوصول إلى كل من شبكة الإنترنت! الذهاب إلى موقع '+
        'محجوب > انقر على أيقونة حولا > تغير بلد العلم > استمتع!'},
    unblocker: {message: 'فك الحظر'},
    accelerator: {message: 'مسرع'},
    on: {message: 'تشغيل'},
    off: {message: 'ايقاف'},
    settings: {message: 'إعدادات'},
    unblocker_site_list: {message: 'قائمة موقع فك الحظر'},
    site_blocked: {message: '$1 محظور?'},
    site_unblocked: {message: '$1 رفع الحظر'},
    changing: {message: 'متغير...'},
    update: {message: 'تحديث'},
    turn_on: {message: 'بداء التشغيل'},
    initializing: {message: 'تهيئة، يرجى الانتظار...'},
    not_working_more_options: {message: 'لا يعمل؟ المزيد من الخيارات...'},
    back_to: {message: 'الرجوع $1 $2'},
    loading: {message: 'تحميل'},
    reload: {message: 'تحديث'},
    more: {message: 'أكثر...'},
    even_more: {message: 'حتى أكثر...'},
    old_error: {message: 'الكروم لاستخدام هولا <a>تحديث</a>'},
    ext_conflict_error: {message:'تدار إعدادات الوكيل الخاص بك عن طريق '+
        'شبكة تمديد آخر. تعطيل هذا التمديد. مواصلة مع هولا '+
        '<a>extensions</a>'},
    unblocker_disabled: {message: 'تم تعطيل فك الحظر'},
    enable: {message: 'تمكين'},
    start: {message: 'بداية'},
    starting: {message: 'ابتداء ...'},
    try_to_reload: {message: 'في محاولة ل <span>تحميل</span>'},
    there_is_error: {message: 'يبدو أن هناك خطأ'},
    reload_hola: {message: 'تحديث هولا'},
    verify_internet: {message: 'التحقق من أن يكون لديك إنترنت'},
    get_help_skype: {message: 'الحصول على مساعدة من مهندس على سكايب: $1'},
    auto_rule_btn: {message: '$1 $2 $3'},
    script_btn: {message: '$1 $2 $3 فاست'},
    access_any_site: {message: 'الوصول إلى أي موقع من أي بلد!'},
    country_and_prefix: {message: '$1 ($2)'},
    old_ff: {message: 'إصدار قديم من فايرفوكس. الصحافة <a>هنا</a> لترقية '},
    old_ff_missing: {message: '(بعض الملامح حولا لا تتوفر في الإصدار الخاص بك)'},
    not_free: {message: '.يحتاج نسخة مجانية من هولا أن تكون إعادة '+
        'تمكين كل 4 ساعات وبرعاية الإعلانات'},
    not_free_get: {message: '.احصل حولا زائد لغير متقطع الخدمة، '+
        'خالية من الاعلانات'},
    hola_on_other_devices: {message: 'هل تريد هولا على أجهزة أخرى؟ '+
        '(إكس بوكس، PS، آبل، آي فون ...). انقر هنا'},
    flag_country: {message: '$1 $2'},
    locale_en: {message: 'الإنجليزية'},
    locale_es: {message: 'الأسبانية'},
    locale_es_419: {message: 'الاسبانية وأمريكا اللاتينية'},
    locale_ar: {message: 'العربية'},
    locale_de: {message: 'الألمانية'},
    locale_fr: {message: 'فرنسي'},
    locale_he: {message: 'العبرية'},
    locale_id: {message: 'الأندونيسية'},
    locale_it: {message: 'الإيطالية'},
    locale_nl: {message: 'الهولندية'},
    locale_pt_BR: {message: 'البرتغالية'},
    locale_ru: {message: 'الروسية'},
    Australia: {message: 'أستراليا'},
    Brazil: {message: 'البرازيل'},
    Canada: {message: 'كندا'},
    Chile: {message: 'تشيلي'},
    Denmark: {message: 'الدنمارك'},
    Egypt: {message: 'مصر'},
    France: {message: 'فرنسا'},
    Germany: {message: 'ألمانيا'},
    'Hong Kong': {message: 'هونج كونج S.A.R.'},
    India: {message: 'الهند'},
    Ireland: {message: 'أيرلندا'},
    Italy: {message: 'إيطاليا'},
    Netherlands: {message: 'هولندا'},
    Poland: {message: 'بولندا'},
    Russia: {message: 'روسيا'},
    Singapore: {message: 'سنغافورة'},
    Spain: {message: 'إسبانيا'},
    Sweden: {message: 'السويد'},
    Switzerland: {message: 'سويسرا'},
    Turkey: {message: 'تركيا'},
    'Great Britain': {message: 'بريطانيا العظمى'},
    'United States': {message: 'الولايات المتحدة'},
};

return E; });
