{
    "$1 $2 $3 fast": "$1 $2 $3 szybko", 
    "$1 VPN": "$1 VPN", 
    "$1 blocked?": "$1 zablokowane?", 
    "$1 unblocked": "$1 odblokowane", 
    "(some Hola features are not available on your version)": "(niektóre funkcje Hola nie są dostępne w twojej wersji)", 
    "Accelerator": "Akcelerator", 
    "Access ALL of the Internet! Go to blocked site -> click Hola icon -> change country flag -> ENJOY!": "Dostęp do CAŁEGO internetu! Przejdź do blokowanej strony -> kliknij ikonkę Hola -> zmien flagę kraju -> ENJOY!", 
    "Access any site from any country, free": "Dostęp do każdej strony z każdego kraju, za darmo", 
    "Author site: $1": "Autor strony: $1", 
    "Author: $1": "Autor: $1", 
    "Enable": "Uruchom", 
    "Get Hola Plus for un-interrupted, ad-free service.": "Pobierz Hola Plus dla nieprzerwanej usługi bez reklam.", 
    "Get help from engineer over skype: $1": "Uzyskaj pomoc poprzez od inżyniera Skype: $1", 
    "Hola": "Hola", 
    "Hola Better Internet": "Hola - lepszy internet", 
    "Hola cannot work properly because another extension is controlling your proxy settings. Please disable other extensions that you think might control your proxy settings in <a>extensions</a> (such as ad-blockers, other VPN services, etc.).": "ola nie może działać prawidłowo, ponieważ inne rozszerzenie kontroluje twoje ustawienia proxy. Wyłącz proszę inne rozszerzenia, które mogą kontrolować ustawienia proxy (takie jak ad-blocki lub inne VPNy itp)", 
    "Improve translation": "ulepsz tłumaczenie", 
    "Initializing...": "Inicjalizacja...", 
    "Loading": "Ładowanie", 
    "Number of users that pressed not working": "Ilość użytkowników, którzy wybrali \"nie działa\"", 
    "Number of users that use this option": "Ilość użytkowników korzystających z tej opcji", 
    "OFF": "OFF", 
    "ON": "ON", 
    "Old version of Firefox. Press <a>here</a> to upgrade.": "Stara wersja Firefoxa. Kliknij <a>tutaj</a> by go zaktualizować.", 
    "Reload": "Przeładuj", 
    "Reload Hola": "Przeładuj Hola", 
    "Settings": "Ustawienia", 
    "Starting...": "rozpoczynam...", 
    "The free version of Hola needs to be re-enabled every 4 hours and is sponsored by ads.": "Darmowa wersja dodatku Hola musi być ponownie uruchamiana co 4 godziny i jest sponsorowana przez reklamy.", 
    "There seems to be an error": "Mamy problem", 
    "Try to <span>reload</span>": "Spróbuj <span>odświeżyć</span>", 
    "Turn on to get started": "Uruchom by rozpocząć", 
    "Unblocker": "odblokować", 
    "Unblocker is disabled": "Hola jest wyłączony", 
    "Unblocker site list": "Strony które możesz odblokować", 
    "Update": "Aktualizuj", 
    "Verify you have Internet": "Sprawdź czy masz dostęp do internetu", 
    "Very old version of Chrome, <a>update</a> Chrome to use Hola": "Bardzo stara wersja Google Chrome, <a>zaktualizuj</a> Chrome by móc używać Hola", 
    "Want Hola on other devices? (Xbox, PS, Apple TV, iPhone...). Click here": "Potrzebujesz Hola na innych urządzeniach? (Xbox, PS, Apple TV, iPhone...). Kliknij tutaj.", 
    "back to $1 $2": "powrót do $1 $2", 
    "changing...": "uwalniam...", 
    "even more...": "jeszcze więcej...", 
    "more...": "więcej...", 
    "not working? more options...": "nie działa? więcej opcji...", 
    "start": "rozpocznij"
}
