'use strict'; /*jshint browser:true, es5:true*/
define(function(){
var E = {
    access_any_site: {message: 'Visita qualsiasi sito, ovunque!'},
    unblocker_site_list: {message: 'Elenco dei siti unblocker'},
    settings: {message: 'impostazioni'},
    site_blocked: {message: '$1 bloccato?'},
    site_unblocked: {message: '$1 sbloccato'},
    more: {message: 'di piÃ¹...'},
    not_working_more_options: {message: 'non funziona? piÃ¹ opzioni...'},
    even_more: {message: 'ancora di piÃ¹...'},
    back_to: {message: 'torna a $1 $2'},
    unblocker: {message: 'Sbloccatore'},
    accelerator: {message: 'Acceleratore'},
    on: {message: 'ON'},
    off: {message: 'OFF'},
    turn_on: {message: 'Attiva per iniziare'},
    unblocker_disabled: {message: 'sbloccatore Ã¨ disabilitato'},
    enable: {message: 'Abilita'},
    app_name: {message: 'Hola Better Internet'},
    app_desc: {message: 'Accedere a tutti gli Internet! Vai sul sito '+
        'bloccato > clicca sull\'icona Hola > cambia la bandiera '+
        'del paese > GODITI IL SITO!'},
    changing: {message: 'cambiando...'},
    update: {message: 'Aggiorna'},
    initializing: {message: 'Inizializzazione, si prega di attendere...'},
    loading: {message: 'Caricamento in corso'},
    reload: {message: 'Ricarica'},
    old_error: {message: 'Versione di Chrome molto vecchia. Chrome '+
        'per utilizzare Hola. <a>Aggiorna</a>'},
    ext_conflict_error: {message:'Le impostazioni del tuo proxy di rete '+
        'sono attualmente gestite da un\'altra estensione. Disabilita '+
        'quell\'estensione, per continuare con Hola <a>extensions</a>'},
    start: {message: 'start'},
    starting: {message: 'Avvio...'},
    try_to_reload: {message: 'Prova a <span>reload</span>'},
    there_is_error: {message: 'Sembra che ci sia un errore'},
    reload_hola: {message: 'Ricarica Hola'},
    verify_internet: {message: 'Verificare di avere Internet'},
    get_help_skype: {message: 'Get aiuto da ingegnere su skype: $1'},
    auto_rule_btn: {message: '$1 $2 $3'},
    script_btn: {message: '$1 $2 $3 veloce'},
    country_and_prefix: {message: '$1 ($2)'},
    old_ff: {message: 'Old versione di Firefox. Comunicato <a>qui</a> '+
        'per l\'aggiornamento.'},
    old_ff_missing: {message: '(alcune caratteristiche Hola non sono '+
        'disponibili sulla versione)'},
    not_free: {message: 'La versione gratuita di Hola deve essere '+
        'riattivato ogni 4 ore ed Ã¨ sponsorizzato da annunci.'},
    not_free_get: {message: 'Get Hola Plus per ininterrotto, '+
        'servizio senza pubblicitÃ '},
    hola_on_other_devices: {message: 'Vuoi Hola su altri dispositivi? '+
        '(Xbox, PS, Apple TV, iPhone ...). Clicca qui'},
    flag_country: {message: '$1 $2'},
    locale_en: {message: 'Inglese'},
    locale_es: {message: 'Spagnolo'},
    locale_es_419: {message: 'Spagnolo, America Latina'},
    locale_ar: {message: 'Arabo'},
    locale_de: {message: 'Tedesca'},
    locale_fr: {message: 'Francese'},
    locale_he: {message: 'Ebraico'},
    locale_id: {message: 'Indonesia'},
    locale_it: {message: 'Italiana'},
    locale_nl: {message: 'Olandese'},
    locale_pt_BR: {message: 'Portoghese'},
    locale_ru: {message: 'Russa'},
    Australia: {message: 'Australia'},
    Brazil: {message: 'Brasile'},
    Canada: {message: 'Canada'},
    Chile: {message: 'Cile'},
    Denmark: {message: 'Danimarca'},
    Egypt: {message: 'Egitto'},
    France: {message: 'Francia'},
    Germany: {message: 'Germania'},
    'Hong Kong': {message: 'Hong Kong'},
    India: {message: 'India'},
    Ireland: {message: 'Irlanda'},
    Italy: {message: 'Italia'},
    Netherlands: {message: 'Paesi Bassi'},
    Poland: {message: 'Polonia'},
    Russia: {message: 'Russia'},
    Singapore: {message: 'Singapour'},
    Spain: {message: 'Spagna'},
    Sweden: {message: 'Svezia'},
    Switzerland: {message: 'Svizzera'},
    Turkey: {message: 'Turchia'},
    'Great Britain': {message: 'Regno Unito'},
    'United States': {message: 'Stati Uniti'},
};

return E; });
