'use strict'; /*jshint browser:true, es5:true*/
define(function(){
var E = {
    access_any_site: {message: 'Toegang tot een site uit elk land!'},
    unblocker_site_list: {message: 'Unblocker sitelijst'},
    settings: {message: 'instellingen'},
    site_blocked: {message: '$1 geblokkeerd?'},
    site_unblocked: {message: '$1 gedeblokkeerd'},
    more: {message: 'meer...'},
    not_working_more_options: {message: 'Werkt het niet? Meer opties...'},
    even_more: {message: 'nog...'},
    back_to: {message: 'terug naar $1 $2'},
    unblocker: {message: 'Ontblokker'},
    accelerator: {message: 'Versneller'},
    on: {message: 'AAN'},
    off: {message: 'UIT'},
    turn_on: {message: 'Schakel aan om aan de slag te gaan'},
    unblocker_disabled: {message: 'ontstopper is uitgeschakeld'},
    enable: {message: 'Enable'},
    app_name: {message: 'Hola Beter Internet'},
    app_desc: {message: 'Toegang tot alle van het internet! Ga naar de '+
        'geblokkeerde website > klik op het Hola icoon > Wijzig land '+
        'vlag > Geniet!'},
    changing: {message: 'veranderen...'},
    update: {message: 'Bijwerken'},
    initializing: {message: 'Initialiseren, even geduld aub...'},
    loading: {message: 'Aan het laden'},
    reload: {message: 'Vernieuwen'},
    old_error: {message: 'Zeer oude versie van Chrome. Chrome om te '+
        'Hola gebruiken <a>Bijwerken</a>'},
    ext_conflict_error: {message:'Je netwerk proxy-instellingen worden '+
        'beheerd door een ander toestel. Uitschakelen die extentie, om '+
        'door te gaan met Hola. <a>extensions</a>'},
    start: {message: 'start'},
    starting: {message: 'Starting...'},
    try_to_reload: {message: 'Probeer <span>reload</span>'},
    there_is_error: {message: 'Er schijnt een fout te zijn'},
    reload_hola: {message: 'Reload Hola'},
    verify_internet: {message: 'Controleer je Internet'},
    get_help_skype: {message: 'Krijg hulp van ingenieur dan skype: $1'},
    auto_rule_btn: {message: '$1 $2 $3'},
    script_btn: {message: '$1 $2 $3 fast'},
    country_and_prefix: {message: '$1 ($2)'},
    old_ff: {message: 'Oude versie van Firefox. '+
        'Druk <a>hier</a> om te upgraden.'},
    old_ff_missing: {message: '(sommige Hola functies zijn niet '+
        'beschikbaar op uw versie)'},
    not_free: {message: 'De gratis versie van Hola moet opnieuw worden '+
        'ingeschakeld om de 4 uur en wordt gesponsord door advertenties.'},
    not_free_get: {message: 'Krijg Hola Plus voor ononderbroken, '+
        'ad-free dienst.'},
    hola_on_other_devices: {message: 'Wil Hola op andere apparaten? '+
        '(Xbox, PS, Apple TV, iPhone ...). Klik hier'},
    flag_country: {message: '$1 $2'},
    locale_en: {message: 'Engels'},
    locale_es: {message: 'Spaans'},
    locale_es_419: {message: 'Spaans, Latijns-Amerika'},
    locale_ar: {message: 'Arabisch'},
    locale_de: {message: 'Duitse'},
    locale_fr: {message: 'Franse'},
    locale_he: {message: 'Hebreeuws'},
    locale_id: {message: 'Indonesisch'},
    locale_it: {message: 'Italiaanse'},
    locale_nl: {message: 'Nederlandse'},
    locale_pt_BR: {message: 'Portugees'},
    locale_ru: {message: 'Russische'},
    Australia: {message: 'AustraliÃ«'},
    Brazil: {message: 'BraziliÃ«'},
    Canada: {message: 'Canada'},
    Chile: {message: 'Chili'},
    Denmark: {message: 'Denemarken'},
    Egypt: {message: 'Egypte'},
    France: {message: 'Frankrijk'},
    Germany: {message: 'Duitsland'},
    'Hong Kong': {message: 'Hongkong'},
    India: {message: 'India'},
    Ireland: {message: 'Ierland'},
    Italy: {message: 'ItaliÃ«'},
    Netherlands: {message: 'Nederland'},
    Poland: {message: 'Polen'},
    Russia: {message: 'Rusland'},
    Singapore: {message: 'Singapore'},
    Spain: {message: 'Spanje'},
    Sweden: {message: 'Zweden'},
    Switzerland: {message: 'Zwitserland'},
    Turkey: {message: 'Turkije'},
    'Great Britain': {message: 'Verenigd Koninkrijk'},
    'United States': {message: 'Verenigde Staten'},
};

return E; });
