'use strict'; /*jshint browser:true, es5:true*/
define(function(){
var E = {
    app_name: {message: 'Улучшенный интернет с Hola'},
    app_desc: {message: 'доступ ко всему Интернету! Зайдите '+
        'на заблокированный сайт > нажмите на значок Hola > выберите флаг '+
        'страны > НАСЛАЖДАЙТЕСЬ!'},
    unblocker: {message: 'Разблокировщик'},
    accelerator: {message: 'Ускоритель'},
    on: {message: 'Вкл'},
    off: {message: 'Выкл'},
    settings: {message: 'настройки'},
    unblocker_site_list: {message: 'Список сайтов для разблокировки'},
    site_blocked: {message: '$1 заблокирован?'},
    site_unblocked: {message: '$1 Разблокирован'},
    changing: {message: 'замена...'},
    update: {message: 'Обновление'},
    turn_on: {message: 'Включите, чтобы начать работу'},
    initializing: {message: 'Загрузка, пожалуйста, подождите...'},
    not_working_more_options: {message: 'не работает? Другие варианты...'},
    back_to: {message: 'вернуться к $1 $2'},
    loading: {message: 'Загрузка'},
    reload: {message: 'Перезагрузить'},
    more: {message: 'еще...'},
    even_more: {message: 'еще больше...'},
    old_error: {message: 'Очень старая версия Chrome. Обновите Chrome '+
        'для того, чтобы использовать Hola. <a>Обновление</a>'},
    ext_conflict_error: {message:'Сетевые параметры прокси которые '+
        'управляются другим расширением браузера. Отключите другие '+
        '<a>расширения</a>, чтобы испольтзовать Hola.'},
    unblocker_disabled: {message: 'Разблокировщик отключен'},
    enable: {message: 'Включить'},
    start: {message: 'Пуск'},
    starting: {message: 'Запускается...'},
    try_to_reload: {message: 'Попробуйте <span>перезапуск</span>'},
    there_is_error: {message: 'Там, кажется, ошибка'},
    reload_hola: {message: 'Перезапустить Hola'},
    verify_internet: {message: 'Убедитесь, что у вас есть Интернет'},
    get_help_skype: {message: 'Получить помощь от инженера по Skype: $1'},
    auto_rule_btn: {message: '$1 $2 $3'},
    script_btn: {message: '$1 $2 $3 быстрых'},
    access_any_site: {message: 'Доступ к любому сайту из любой страны!'},
    country_and_prefix: {message: '$1 ($2)'},
    old_ff: {message: 'Версия Firefox. Нажмите <a>здесь</a> для обновления.'},
    old_ff_missing: {message: '(некоторые функции Hola могут быть '+
        'недоступны на вашей версии Firefox)'},
    not_free: {message: 'Бесплатную версию Hola нужно включать заново '+
        'каждые 4 часа. Вам так же будут показываться баннеры.'},
    not_free_get: {message: 'Получить Hola плюс для каких-либо '+
        'перебоев, без рекламы службе.'},
    hola_on_other_devices: {message: 'Хотите Hola в других устройствах? '+
        '(Xbox, PS, Apple TV, iPhone ...). Нажмите здесь'},
    flag_country: {message: '$1 $2'},
    locale_en: {message: 'Английский'},
    locale_es: {message: 'Испанский'},
    locale_es_419: {message: 'Испанский, Латинская Америка'},
    locale_ar: {message: 'Арабский'},
    locale_de: {message: 'Немецкий'},
    locale_fr: {message: 'Французский'},
    locale_he: {message: 'Иврит'},
    locale_id: {message: 'Индонезийский'},
    locale_it: {message: 'Итальянский'},
    locale_nl: {message: 'Голландский'},
    locale_pt_BR: {message: 'Португальский'},
    locale_ru: {message: 'Русский'},
    Australia: {message: 'Австралия'},
    Brazil: {message: 'Бразилия'},
    Canada: {message: 'Канада'},
    Chile: {message: 'Чили'},
    Denmark: {message: 'Дания'},
    Egypt: {message: 'Египет'},
    France: {message: 'Франция'},
    Germany: {message: 'Германия'},
    'Hong Kong': {message: 'Гонгконг'},
    India: {message: 'Индия'},
    Ireland: {message: 'Ирландия'},
    Italy: {message: 'Италия'},
    Netherlands: {message: 'Нидерланды'},
    Poland: {message: 'Польша'},
    Russia: {message: 'Россия'},
    Singapore: {message: 'Сингапур'},
    Spain: {message: 'Испания'},
    Sweden: {message: 'Швеция'},
    Switzerland: {message: 'Швейцария'},
    Turkey: {message: 'Турция'},
    'Great Britain': {message: 'Великобритания'},
    'United States': {message: 'США'},
};

return E; });
