{
    "$1 $2 $3 fast": "$1 $2 $3 snel", 
    "$1 VPN": "$1 VPN", 
    "$1 blocked?": "$1 geblokkeerd?", 
    "$1 unblocked": "$1 gedeblokkeerd", 
    "(some Hola features are not available on your version)": "(sommige functies van Hola zijn niet beschikbaar in deze versie)", 
    "Accelerator": "Versneller", 
    "Access ALL of the Internet! Go to blocked site -> click Hola icon -> change country flag -> ENJOY!": "Access ALL of the Internet! Go to blocked site -> click Hola icon -> change country flag -> ENJOY!", 
    "Access any site from any country, free": "Toegang tot elke site vanuit elk land, gratis", 
    "Author site: $1": "Author site: $1", 
    "Author: $1": "Author: $1", 
    "Enable": "Inschakelen", 
    "Get Hola Plus for un-interrupted, ad-free service.": "Neem Hola Plus voor een ononderbroken, dienst, zonder advertenties.", 
    "Get help from engineer over skype: $1": "Krijg hulp van een expert via Skype: $1", 
    "Hola": "Hola", 
    "Hola Better Internet": "Hola beter internet", 
    "Hola cannot work properly because another extension is controlling your proxy settings. Please disable other extensions that you think might control your proxy settings in <a>extensions</a> (such as ad-blockers, other VPN services, etc.).": "ola kan niet correct werken, omdat een andere extensie je proxyinstellingen beheert. Schakel de andere extentie die waarschijnlijk je proxyinstellingen beheert uit in <a>Extensies</a> (bijvoorbeeld ad-blockers, andere VPN-services, etc.).", 
    "Improve translation": "Verbeter vertaling", 
    "Initializing...": "Inschakelen...", 
    "Loading": "Aan het laden", 
    "Number of users that pressed not working": "Number of users that pressed \"not working\"", 
    "Number of users that use this option": "Number of users that use this option", 
    "OFF": "UIT", 
    "ON": "AAN", 
    "Old version of Firefox. Press <a>here</a> to upgrade.": "Oude versie van Firefox. Klik <a>hier</a> om te upgraden.", 
    "Reload": "Vernieuwen", 
    "Reload Hola": "Start Hola opnieuw", 
    "Settings": "Instellingen", 
    "Starting...": "Opstarten...", 
    "The free version of Hola needs to be re-enabled every 4 hours and is sponsored by ads.": "De gratis versie van Hola moet om de 4 uur opnieuw worden ingeschakeld en wordt gesponsord door advertenties.", 
    "There seems to be an error": "Er lijkt een fout te zijn", 
    "Translate to your language": "Vertaal naar jouw taal", 
    "Try to <span>reload</span>": "Probeer <span>opnieuw te laden</span>", 
    "Turn on to get started": "Schakel in om aan de slag te gaan", 
    "Unblocker": "Unblocker", 
    "Unblocker is disabled": "Unblocker is uitgeschakeld", 
    "Unblocker site list": "Unblocker sitelijst", 
    "Update": "Bijwerken", 
    "Verify you have Internet": "Controleer je internetverbinding", 
    "Very old version of Chrome, <a>update</a> Chrome to use Hola": "Zeer oude versie van Chrome, <a>update</a> Chrome om Hola te gebruiken", 
    "Want Hola on other devices? (Xbox, PS, Apple TV, iPhone...). Click here": "Hola ook op andere apparaten? (Xbox, PS, Apple TV, iPhone ...). Klik hier", 
    "back to $1 $2": "terug naar $1 $2", 
    "changing...": "veranderen...", 
    "even more...": "meer...", 
    "more...": "meer...", 
    "not working? more options...": "Werkt het niet? Meer opties...", 
    "start": "start"
}
